### ISSUE TITLE
Help with using the IFC parser needed

### ISSUE THREAD

**Issue by rebeccasc** [opensourceBIM/BuildingSMARTLibrary#1]
I'm planning to use your IFC parser for an open source project but cannot make it work. What I want to do is to parse an .ifc file containing `ISO-10303-21;` and `FILE_SCHEMA(('IFC2X3'));`. Which parser do I have to use and is the parser up to date? Is there a documentation of how to use the parser? Thanks!

**Comment by aothms** [comment]
Hi, I read up on the GSoC page. Interesting project. I would propose you either use something like jSDAI if a pure Java code base is important to you. It's a general code generation and parser library for generic STEP schemas. It will leave you with a ton of work though to implement the geometry handling. IFC is a complex engineering format with procedural geometry definitions. There aren't really geometry libraries implemented in Java that offer a good basis for this. You can also pick one of the open source libraries with full support for IFC geometry definitions such as https://github.com/IfcOpenShell/IfcOpenShell/ (I'm the maintainer) or https://github.com/xBimTeam/ (there are others) both rely on the foss Open CASCADE geometry library. What people typically do is build some sort of pipeline that transforms the IFC model into a 'usable' geometry format such as Collada (http://www.ifcopenshell.org/ifcconvert can do this) and then start to do the domain specific interpretations.

**Comment by rebeccasc** [comment]
@aothms Thank you for the answer.
I do need pure Java code thats why it's quite difficult. I've had a look at your suggestions and as you have said just the C++ projects solve the problem with geometry handling. 
I guess you have a lot of experiences working with IFC. Might it be helpful to write a Java parser? This idea will not be possible within my GSoC project but maybe afterwards. What do you think?

**Comment by aothms** [comment]
> Might it be helpful to write a Java parser?

As I said, do look into jSDAI [0]. SDAI is a standardized programming interface to EXPRESS. It's rather ancient, but gets the job done. Otherwise something like ANTLR should get a you up and running quick enough, there are g4 files for both the model files (part 21) as well as the schema language (part 11 of the standard) but code generation for the class hierarchy is still something you'd have to implement yourself. You probably do not want to read these files without a static interface that will get you forward and inverse attributes by name (ie you need to parse the schema and generate code). I must say I don't know how easy it is in Java to use generics to parametrize the schema version though.

Another option is to use the compiled C++ executables and communicate using stdin stdout. That's what BIMserver (the repo you're commenting on is the parser of BIMserver) does [1]. It's a light weight serialization protocol to get object shapes from a specific purpose executable. Or use SWIG and/or JNI.  People jump to these hoops for a reason, there simply isn't a good foss technology stack in Java for these kind of geometries. You'll get pretty far with simple extrusions that make up most of the IFC files, but for the boolean operations and complex sweeps I'm afraid you're going to hit a wall.

Otherwise perhaps @hlg has some ideas. Also a BIM/GIS researcher and more familiar to Java. @hlg, @rebeccasc wants to read IFC files into Open Street map for GSoC.

[0] https://www.jsdai.net/
[1] https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin

**Comment by hlg** [comment]
Great project of yours @rebeccasc!

This P21 (SPF) parser here is quite ancient and not actually used much. JavaCC is a solid base at least, but the grammar has some caveats. I have just tried it out with one of the official IFC4 example files and one thing I realized (and remember from tinkering with the grammar a while ago) is that it does not handle block comments well, i.e. it greedily ignores everything between the first and the last block comment. I attach a [comment-free version of the file](https://github.com/opensourceBIM/BuildingSMARTLibrary/files/4871310/wall-with-opening-and-window-clean-comment.ifc.txt) for you to test. I can also see if I find the fix for that comment issue in the darker corners of my archives.There may be other issues as well though. Judging from your preliminary code, you seem to properly use the parser. What problems do you experience with the parser? One thing to be aware of (see disclaimer in Jakob's README) is memory consumption as IFC files can grow quite large. For your current project I'd suggest to optimize IFC files for your use case upfront.

If you try JSDAI, I assume you would not have these issues, it is really mature. It employs some disk cache to relieve RAM, but I remember it being a bit cumbersome to manage the resources for the cache. Also, the API may seem a bit over the top for IFC, because method signatures include parameters to handle multiple inheritance. The IFC schemas use only single inheritance, thus you would have to push around some null parameters. There was another Java parser / code generator which I had checked a while ago, but I think it had no active development anymore already at the time.

As you already discussed, even with parsing solved you will still have to interpret geometry and the model is quite complex. It is not that Java is not good enough for this, but no-one has taken the trouble to do it in Java and if so they did not publish it under an open source license. There is for example the [APSTEX ifctoolbox](http://www.apstex.com/) based on Java3D (if they did not change), but it is not open.

Another option, which I am mostly using, is to store IFC files in BIMserver and connect with a client. This way you can query only those parts of the data that you need and go easy on memory. You can also transform the data on the server or in a service and serialize to other formats. BIMserver uses the EXPRESS parser and EXPRESS to EMF conversion from this repository, but does implement its own SPF parser which is in the [IfcPlugins repository](https://github.com/opensourceBIM/IfcPlugins). You can (and I do sometimes) use the non-streaming version on its own without the server, but it will again have the memory issue and won't provide you with any pre-processed geometry, since that is done on the server (with IfcOpenShell). It uses (EMF-)generated Java classes for the schema elements (early binding, static EXPRESS types), while this buildingsmart parser is late-binding and with dynamic EXPRESS types you don't have to fix the schema at compile time.

**Comment by hlg** [comment]
Oh, btw. you can use

* `EntityInstance.getAttributeValueBNasEntityInstance` and
* `EntityInstance.getAttributeValueBNasEntityInstanceList` instead of just
* `EntityInstance.getAttributeValueBN`

to get associated entity instances by attribute name (BN) already resolved from the model and not just their local identifier as String.

**Comment by rebeccasc** [comment]
@hlg thanks for the answer.
I also had troubles with the block comments but it's a good idea to opimize the ifc file first. I would like to not do all the geometry handling on my own even if I've already started with it because of the GSoC limited time period. If I want to use the [IfcOpenShell BIMserver-plugin](https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin) instead of this parser, can you give me a short example of how to use it? I figured out there is an `IfcOpenShellModel` that can read my `InputStream` but there is also an `IfcGeomServerClient` object required. What does that do and how do I have to initialize it? 
For me it seems like the BIMserver and it's plugins is a huge project and pretty complex for what I want to do. 
Nevertheless, I would like to know how to use the BIMserver-plugin. Even if I cannot use it right now because of GSoC limited time periods, I can update the plugin I'm working on afterwards with using the BIMserver-plugin.

**Comment by aothms** [comment]
There is a example (runnable cli) for geom server client here https://github.com/opensourceBIM/IfcOpenShell-BIMserver-plugin/blob/master/src/org/ifcopenshell/ClientRunner.java 

Note that this is fairly independent of the bimserver parser, the client is just fed an IFC-SPF file (in case of BIMserver: snippets, for parallelization). I'm not sure what kind of data you require from the IFC model, but if it's only purely explicit geometry with some type labels, the data returned from this client might be sufficient.

**Comment by rebeccasc** [comment]
Okay. Thanks for all the ideas and the help. I will have a look at it!

**Comment by hlg** [comment]
I just want to give you some more information about the role of the IfcOpenShellEngine with BIMserver, in case you have not figured out yet by looking at the `ClientRunner`.

`IfcGeomServerClient` will download a recent IfcOpenShell build for the respective OS, spawn a new process and run [IfcGeomServer](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.6.0/src/ifcgeomserver), a commandline interface to IfcOpenShell. It then pipes the inputstream to `IfcGeomServer` and receives binary geometry data (tesselated 3D geometry). `IfcOpenShellModel`, which is just a wrapper around the client to adapt to BIMserver's `RenderEngineModel`.

BIMserver allows to switch between different render engine implementations (as plugins). Render engines are used for the sole purpose of visualization in BIMserver and for that reason the API to IfcOpenShell through the `IfcGeomServerClient` is tailored to that purpose and the options you have to interact with IfcOpenShell are fairly limited. If tesselated 3D geometry is what you need, you should be good. This does not help with parsing the non-geometric parts of the IFC though. If you need, for example, wall names, the stories they are contained in and the like, you would still  have to do the parsing on your own. IfcOpenShell wouldn't be a replacement for a parser, if you use it through the `IfcGeomServer`.
